### ISSUE TITLE
REEEEE DOET NIET

### ISSUE THREAD

**Issue by lucvankessel** [Jesper54/GameShop#1]

**Comment by Jesper54** [comment]
You'll need to install a simple react app yourself and then you can paste this into it.
You also need to do 'yarn add react-router-dom', and now it should be working.

**Comment by lucvankessel** [comment]
SKETIIIIT

**Comment by Jesper54** [comment]
Je bent dik

**Comment by lucvankessel** [comment]
kijk eerst ff naar je eigen weegschaal
